version: "3.9"

services:
  class_build:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./pages:/class_build/pages
      - ./src:/class_build/src
      - ./public:/class_build/public
    ports:
      - 3000:3000
